services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_HOST: db-host
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp-db
    depends_on:
      - db-wp
    networks:
      - wp-network
    profiles:
      - dev
      - production

  ## DEV DATABASE ##
  db-wp:
    image: mysql
    restart: always
    container_name: dev-db
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      wp-network:
        aliases:
          - db-host
    profiles:
      - dev

  ## PRODUCTION DATABASE ##
  db-wp-prod:
    image: mysql
    restart: always
    container_name: production-db
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      wp-network:
        aliases:
          - db-host
    profiles:
      - production
networks:
  wp-network:
